// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YugiohDB;

#nullable disable

namespace YugiohDB.Migrations
{
    [DbContext(typeof(YgoContext))]
    partial class YgoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("YugiohDB.Models.BanlistInfo", b =>
                {
                    b.Property<int>("Banlist_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Banlist_Id"), 1L, 1);

                    b.Property<string>("Ban_GOAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ban_OCG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ban_TCG")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Banlist_Id");

                    b.ToTable("BanlistInfo");
                });

            modelBuilder.Entity("YugiohDB.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"), 1L, 1);

                    b.Property<string>("Archetype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Atk")
                        .HasColumnType("int");

                    b.Property<string>("Attribute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BanlistInfoBanlist_Id")
                        .HasColumnType("int");

                    b.Property<int?>("CardId1")
                        .HasColumnType("int");

                    b.Property<int?>("DeckId")
                        .HasColumnType("int");

                    b.Property<int?>("DeckId1")
                        .HasColumnType("int");

                    b.Property<int?>("DeckId2")
                        .HasColumnType("int");

                    b.Property<int?>("Def")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KonamiCardId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("LinkVal")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Scale")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardId");

                    b.HasIndex("BanlistInfoBanlist_Id");

                    b.HasIndex("CardId1");

                    b.HasIndex("DeckId");

                    b.HasIndex("DeckId1");

                    b.HasIndex("DeckId2");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("YugiohDB.Models.CardSet", b =>
                {
                    b.Property<int>("CardSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardSetId"), 1L, 1);

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rarity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RarityCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardSetId");

                    b.HasIndex("CardId");

                    b.ToTable("CardSets");
                });

            modelBuilder.Entity("YugiohDB.Models.Deck", b =>
                {
                    b.Property<int>("DeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeckId"), 1L, 1);

                    b.Property<string>("DeckName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeckId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("YugiohDB.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"), 1L, 1);

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("CardImageId")
                        .HasColumnType("int");

                    b.Property<string>("ImageLocalUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLocalUrlSmall")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrlSmall")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.HasIndex("CardId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("YugiohDB.Models.MiscInfo", b =>
                {
                    b.Property<int>("MiscId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MiscId"), 1L, 1);

                    b.Property<string>("BetaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("DownVotes")
                        .HasColumnType("int");

                    b.Property<int>("HasEffect")
                        .HasColumnType("int");

                    b.Property<int>("KonamiId")
                        .HasColumnType("int");

                    b.Property<string>("OcgDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcgDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreatedAs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpVotes")
                        .HasColumnType("int");

                    b.Property<long>("Views")
                        .HasColumnType("bigint");

                    b.Property<int>("ViewsWeek")
                        .HasColumnType("int");

                    b.HasKey("MiscId");

                    b.HasIndex("CardId");

                    b.ToTable("MiscInformation");
                });

            modelBuilder.Entity("YugiohDB.Models.Price", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceId"), 1L, 1);

                    b.Property<string>("Amazon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("CardMarket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoolStuffInc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ebay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcgPlayer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PriceId");

                    b.HasIndex("CardId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("YugiohDB.Models.SetInfo", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SetId"), 1L, 1);

                    b.Property<int>("NumOfCards")
                        .HasColumnType("int");

                    b.Property<string>("SetCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcgDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SetId");

                    b.ToTable("SetInformation");
                });

            modelBuilder.Entity("YugiohDB.Models.Card", b =>
                {
                    b.HasOne("YugiohDB.Models.BanlistInfo", "BanlistInfo")
                        .WithMany()
                        .HasForeignKey("BanlistInfoBanlist_Id");

                    b.HasOne("YugiohDB.Models.Card", null)
                        .WithMany("Data")
                        .HasForeignKey("CardId1");

                    b.HasOne("YugiohDB.Models.Deck", null)
                        .WithMany("ExtraDeck")
                        .HasForeignKey("DeckId");

                    b.HasOne("YugiohDB.Models.Deck", null)
                        .WithMany("MainDeck")
                        .HasForeignKey("DeckId1");

                    b.HasOne("YugiohDB.Models.Deck", null)
                        .WithMany("SideDeck")
                        .HasForeignKey("DeckId2");

                    b.Navigation("BanlistInfo");
                });

            modelBuilder.Entity("YugiohDB.Models.CardSet", b =>
                {
                    b.HasOne("YugiohDB.Models.Card", null)
                        .WithMany("CardSets")
                        .HasForeignKey("CardId");
                });

            modelBuilder.Entity("YugiohDB.Models.Image", b =>
                {
                    b.HasOne("YugiohDB.Models.Card", null)
                        .WithMany("CardImages")
                        .HasForeignKey("CardId");
                });

            modelBuilder.Entity("YugiohDB.Models.MiscInfo", b =>
                {
                    b.HasOne("YugiohDB.Models.Card", null)
                        .WithMany("MiscInfo")
                        .HasForeignKey("CardId");
                });

            modelBuilder.Entity("YugiohDB.Models.Price", b =>
                {
                    b.HasOne("YugiohDB.Models.Card", null)
                        .WithMany("CardPrices")
                        .HasForeignKey("CardId");
                });

            modelBuilder.Entity("YugiohDB.Models.Card", b =>
                {
                    b.Navigation("CardImages");

                    b.Navigation("CardPrices");

                    b.Navigation("CardSets");

                    b.Navigation("Data");

                    b.Navigation("MiscInfo");
                });

            modelBuilder.Entity("YugiohDB.Models.Deck", b =>
                {
                    b.Navigation("ExtraDeck");

                    b.Navigation("MainDeck");

                    b.Navigation("SideDeck");
                });
#pragma warning restore 612, 618
        }
    }
}
